apiVersion: v1
kind: ConfigMap
metadata:
  name: lead-runtime-config
  namespace: law-application
data:
  OIDC_ISSUER_URL: http://localhost:8082/realms/law
  OIDC_CLIENT_ID: attorney-web
  OIDC_JWKS_URL: http://keycloak.keycloak.svc.cluster.local:8082/realms/law/protocol/openid-connect/certs
  OIDC_TOKEN_URL: http://keycloak.keycloak.svc.cluster.local:8082/realms/law
  TEMPORAL_ADDRESS: temporal-frontend.temporal.svc.cluster.local:7233
  TEMPORAL_NAMESPACE: alma-law-namespace