apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-k8-cluster-1
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prsanghavi/local-k8-cluster-1.git
    targetRevision: HEAD
    # Change this if the deployable manifests/chart are below the repository root.
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
