apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: keycloak
  password: keycloak-local-db-password
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-keycloak
  namespace: database
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: postgres