apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.neo4j.com/neo4j
    chart: neo4j
    targetRevision: 2026.9.0
    helm:
      releaseName: neo4j
      valuesObject:
        neo4j:
          name: neo4j
          edition: community
          passwordFromSecret: neo4j-auth
        services:
          neo4j:
            enabled: true
            spec:
              type: LoadBalancer
            ports:
              http:
                enabled: true
              bolt:
                enabled: true
        volumes:
          data:
            mode: defaultStorageClass
  destination:
    server: https://kubernetes.default.svc
    namespace: graphdb-ns-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


 