apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.runix.net
    chart: pgadmin4
    targetRevision: '*'
    helm:
      valuesObject:
        auth:
          email: admin@local.test
          password: admin
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
