apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox-application-transparent-mitmproxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/Pratik-Sanghavi/sandbox-application.git
    targetRevision: main
    path: sandbox-system/transparent-mitmproxy/manifests
    plugin:
      name: sops-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: sandbox-ns-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
