apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox-namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/Pratik-Sanghavi/common_infra.git
    targetRevision: main
    path: apps/sandbox/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
