apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transfer-pricing-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Pratik-Sanghavi/transfer-pricing-application.git
    targetRevision: transfer-pricing
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: transfer-pricing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
